### ISSUE TITLE
Bug found index out of range

### ISSUE THREAD

**Issue by pubestpubest** [Project-Computer-Architecture-67-AAAUPP/Project-Computer-Architecture-67-AAAUPP#5]
https://github.com/Project-Computer-Architecture-67-AAAUPP/Project-Computer-Architecture-67-AAAUPP/blob/010a2bfecc842fdfa4466f918397ba0e0106e0de/Part2_behavioral%20simulator/behavioralSimulator.py#L82

```
pubest@pubest Part2_behavioral simulator % python3 behavioralSimulator.py
memory[0]=8454150
memory[1]=9043974
memory[2]=655361
memory[3]=16842754
memory[4]=16842749
memory[5]=29360128
memory[6]=25165824
memory[7]=5
memory[8]=-1
memory[9]=2
memory[10]=29360128

@@@
state:
        pc 0
        memory:
                mem[ 0 ] 8454150
                mem[ 1 ] 9043974
                mem[ 2 ] 655361
                mem[ 3 ] 16842754
                mem[ 4 ] 16842749
                mem[ 5 ] 29360128
                mem[ 6 ] 25165824
                mem[ 7 ] 5
                mem[ 8 ] -1
                mem[ 9 ] 2
                mem[ 10 ] 29360128
        registers:
                reg[ 0 ] 0
                reg[ 1 ] 0
                reg[ 2 ] 0
                reg[ 3 ] 0
                reg[ 4 ] 0
                reg[ 5 ] 0
                reg[ 6 ] 0
                reg[ 7 ] 0
end state

@@@
state:
        pc 1
        memory:
                mem[ 0 ] 8454150
                mem[ 1 ] 9043974
                mem[ 2 ] 655361
                mem[ 3 ] 16842754
                mem[ 4 ] 16842749
                mem[ 5 ] 29360128
                mem[ 6 ] 25165824
                mem[ 7 ] 5
                mem[ 8 ] -1
                mem[ 9 ] 2
                mem[ 10 ] 29360128
        registers:
                reg[ 0 ] 0
                reg[ 1 ] 25165824
                reg[ 2 ] 0
                reg[ 3 ] 0
                reg[ 4 ] 0
                reg[ 5 ] 0
                reg[ 6 ] 0
                reg[ 7 ] 0
end state
Traceback (most recent call last):
  File "/Users/pubest/gits/com-arch-proj/Part2_behavioral simulator/behavioralSimulator.py", line 138, in <module>
    simulate(memory, len(memory))
  File "/Users/pubest/gits/com-arch-proj/Part2_behavioral simulator/behavioralSimulator.py", line 82, in simulate
    reg[regB] = memory[reg[regA] + offsetField]
                ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range```

**Comment by pubestpubest** [comment]
After add try-catch
```pubest@pubest Part2_behavioral simulator % python3 behavioralSimulator.py 
memory[0]=8454150
memory[1]=9043974
memory[2]=655361
memory[3]=16842754
memory[4]=16842749
memory[5]=29360128
memory[6]=25165824
memory[7]=5
memory[8]=-1
memory[9]=2
memory[10]=29360128

@@@
state:
        pc 0
        memory:
                mem[ 0 ] 8454150
                mem[ 1 ] 9043974
                mem[ 2 ] 655361
                mem[ 3 ] 16842754
                mem[ 4 ] 16842749
                mem[ 5 ] 29360128
                mem[ 6 ] 25165824
                mem[ 7 ] 5
                mem[ 8 ] -1
                mem[ 9 ] 2
                mem[ 10 ] 29360128
        registers:
                reg[ 0 ] 0
                reg[ 1 ] 0
                reg[ 2 ] 0
                reg[ 3 ] 0
                reg[ 4 ] 0
                reg[ 5 ] 0
                reg[ 6 ] 0
                reg[ 7 ] 0
end state

@@@
state:
        pc 1
        memory:
                mem[ 0 ] 8454150
                mem[ 1 ] 9043974
                mem[ 2 ] 655361
                mem[ 3 ] 16842754
                mem[ 4 ] 16842749
                mem[ 5 ] 29360128
                mem[ 6 ] 25165824
                mem[ 7 ] 5
                mem[ 8 ] -1
                mem[ 9 ] 2
                mem[ 10 ] 29360128
        registers:
                reg[ 0 ] 0
                reg[ 1 ] 25165824
                reg[ 2 ] 0
                reg[ 3 ] 0
                reg[ 4 ] 0
                reg[ 5 ] 0
                reg[ 6 ] 0
                reg[ 7 ] 0
end state
Error: Memory access out of bounds: 25165830
Current instruction: 0b100010100000000000000110
PC: 1, Opcode: 2, regA: 1, regB: 2, destReg: 6, offsetField: 6
machine halted
total of 2 instructions executed
final state of machine:

@@@
state:
        pc 2
        memory:
                mem[ 0 ] 8454150
                mem[ 1 ] 9043974
                mem[ 2 ] 655361
                mem[ 3 ] 16842754
                mem[ 4 ] 16842749
                mem[ 5 ] 29360128
                mem[ 6 ] 25165824
                mem[ 7 ] 5
                mem[ 8 ] -1
                mem[ 9 ] 2
                mem[ 10 ] 29360128
        registers:
                reg[ 0 ] 0
                reg[ 1 ] 25165824
                reg[ 2 ] 0
                reg[ 3 ] 0
                reg[ 4 ] 0
                reg[ 5 ] 0
                reg[ 6 ] 0
                reg[ 7 ] 0
end state```

**Comment by pubestpubest** [comment]
อาจจะ bug ที่ assembly to machine code
**Edit 1: เพิ่งเห็นว่า assembly คนละอันกัน (แต่ bug ยังอยู่เหมือนเดิม)

**Comment by pubestpubest** [comment]
Assembly to Machine ไม่ตรงกับ spec
<img width="570" alt="image" src="https://github.com/user-attachments/assets/c2ca27b6-58c2-4fb3-9cf2-dcae44959ffe">

<img width="685" alt="image" src="https://github.com/user-attachments/assets/3d0939e5-a506-40a8-b50a-de35ce381c5b">

**Edit 1: เพิ่งเห็นว่า assembly คนละอันกัน (แต่ bug ยังอยู่เหมือนเดิม)

**Comment by pubestpubest** [comment]
แก้ให้เหมือน project spec แล้วแต่มี bug ใหม่ที่ behavioral

https://github.com/Project-Computer-Architecture-67-AAAUPP/Project-Computer-Architecture-67-AAAUPP/blob/16f7d7db7c46f91fa8a59ac49df61cde0b097514/Part1_compile/AssemblyToMachineCode.py#L49-L52
แก้เป็น
```
if offset_field in labels:
                offset = labels[offset_field]
            else:
                offset = int(offset_field)
```

<img width="237" alt="image" src="https://github.com/user-attachments/assets/d5777991-f0e6-4907-968e-74073a1241e4">

```
python3 behavioralSimulator.py
memory[0]=8454151
memory[1]=9043971
memory[2]=655361
memory[3]=16842754
memory[4]=16777218
memory[5]=29360128
memory[6]=25165824
memory[7]=5
memory[8]=-1
memory[9]=2

@@@
state:
        pc 0
        memory:
                mem[ 0 ] 8454151
                mem[ 1 ] 9043971
                mem[ 2 ] 655361
                mem[ 3 ] 16842754
                mem[ 4 ] 16777218
                mem[ 5 ] 29360128
                mem[ 6 ] 25165824
                mem[ 7 ] 5
                mem[ 8 ] -1
                mem[ 9 ] 2
        registers:
                reg[ 0 ] 0
                reg[ 1 ] 0
                reg[ 2 ] 0
                reg[ 3 ] 0
                reg[ 4 ] 0
                reg[ 5 ] 0
                reg[ 6 ] 0
                reg[ 7 ] 0
end state

@@@
state:
        pc 1
        memory:
                mem[ 0 ] 8454151
                mem[ 1 ] 9043971
                mem[ 2 ] 655361
                mem[ 3 ] 16842754
                mem[ 4 ] 16777218
                mem[ 5 ] 29360128
                mem[ 6 ] 25165824
                mem[ 7 ] 5
                mem[ 8 ] -1
                mem[ 9 ] 2
        registers:
                reg[ 0 ] 0
                reg[ 1 ] 5
                reg[ 2 ] 0
                reg[ 3 ] 0
                reg[ 4 ] 0
                reg[ 5 ] 0
                reg[ 6 ] 0
                reg[ 7 ] 0
end state

@@@
state:
        pc 2
        memory:
                mem[ 0 ] 8454151
                mem[ 1 ] 9043971
                mem[ 2 ] 655361
                mem[ 3 ] 16842754
                mem[ 4 ] 16777218
                mem[ 5 ] 29360128
                mem[ 6 ] 25165824
                mem[ 7 ] 5
                mem[ 8 ] -1
                mem[ 9 ] 2
        registers:
                reg[ 0 ] 0
                reg[ 1 ] 5
                reg[ 2 ] -1
                reg[ 3 ] 0
                reg[ 4 ] 0
                reg[ 5 ] 0
                reg[ 6 ] 0
                reg[ 7 ] 0
end state

@@@
state:
        pc 3
        memory:
                mem[ 0 ] 8454151
                mem[ 1 ] 9043971
                mem[ 2 ] 655361
                mem[ 3 ] 16842754
                mem[ 4 ] 16777218
                mem[ 5 ] 29360128
                mem[ 6 ] 25165824
                mem[ 7 ] 5
                mem[ 8 ] -1
                mem[ 9 ] 2
        registers:
                reg[ 0 ] 0
                reg[ 1 ] 4
                reg[ 2 ] -1
                reg[ 3 ] 0
                reg[ 4 ] 0
                reg[ 5 ] 0
                reg[ 6 ] 0
                reg[ 7 ] 0
end state

@@@
state:
        pc 4
        memory:
                mem[ 0 ] 8454151
                mem[ 1 ] 9043971
                mem[ 2 ] 655361
                mem[ 3 ] 16842754
                mem[ 4 ] 16777218
                mem[ 5 ] 29360128
                mem[ 6 ] 25165824
                mem[ 7 ] 5
                mem[ 8 ] -1
                mem[ 9 ] 2
        registers:
                reg[ 0 ] 0
                reg[ 1 ] 4
                reg[ 2 ] -1
                reg[ 3 ] 0
                reg[ 4 ] 0
                reg[ 5 ] 0
                reg[ 6 ] 0
                reg[ 7 ] 0
end state

@@@
state:
        pc 7
        memory:
                mem[ 0 ] 8454151
                mem[ 1 ] 9043971
                mem[ 2 ] 655361
                mem[ 3 ] 16842754
                mem[ 4 ] 16777218
                mem[ 5 ] 29360128
                mem[ 6 ] 25165824
                mem[ 7 ] 5
                mem[ 8 ] -1
                mem[ 9 ] 2
        registers:
                reg[ 0 ] 0
                reg[ 1 ] 4
                reg[ 2 ] -1
                reg[ 3 ] 0
                reg[ 4 ] 0
                reg[ 5 ] 0
                reg[ 6 ] 0
                reg[ 7 ] 0
end state

@@@
state:
        pc 8
        memory:
                mem[ 0 ] 8454151
                mem[ 1 ] 9043971
                mem[ 2 ] 655361
                mem[ 3 ] 16842754
                mem[ 4 ] 16777218
                mem[ 5 ] 29360128
                mem[ 6 ] 25165824
                mem[ 7 ] 5
                mem[ 8 ] -1
                mem[ 9 ] 2
        registers:
                reg[ 0 ] 0
                reg[ 1 ] 4
                reg[ 2 ] -1
                reg[ 3 ] 0
                reg[ 4 ] 0
                reg[ 5 ] 0
                reg[ 6 ] 0
                reg[ 7 ] 0
end state

@@@
state:
        pc 9
        memory:
                mem[ 0 ] 8454151
                mem[ 1 ] 9043971
                mem[ 2 ] 655361
                mem[ 3 ] 16842754
                mem[ 4 ] 16777218
                mem[ 5 ] 29360128
                mem[ 6 ] 25165824
                mem[ 7 ] 5
                mem[ 8 ] -1
                mem[ 9 ] 2
        registers:
                reg[ 0 ] 0
                reg[ 1 ] 4
                reg[ 2 ] -1
                reg[ 3 ] 0
                reg[ 4 ] 0
                reg[ 5 ] 0
                reg[ 6 ] 0
                reg[ 7 ] 0
end state
Traceback (most recent call last):
  File "/Users/pubest/gits/com-arch-proj/Part2_behavioral simulator/behavioralSimulator.py", line 158, in <module>
    simulate(memory, len(memory))
  File "/Users/pubest/gits/com-arch-proj/Part2_behavioral simulator/behavioralSimulator.py", line 66, in simulate
    instruction = memory[pc]
                  ~~~~~~^^^^
IndexError: list index out of range
```

**Comment by Goodl3oyZ** [comment]
Fix logic compile I-type 
![image](https://github.com/user-attachments/assets/88b2e2a7-83bd-4bcd-b177-1f69723b2daf)

**Comment by AutsadaWiriya** [comment]
> Fix logic compile I-type ![image](https://private-user-images.githubusercontent.com/110963173/375007487-88b2e2a7-83bd-4bcd-b177-1f69723b2daf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0ODU2NzYsIm5iZiI6MTcyODQ4NTM3NiwicGF0aCI6Ii8xMTA5NjMxNzMvMzc1MDA3NDg3LTg4YjJlMmE3LTgzYmQtNGJjZC1iMTc3LTFmNjk3MjNiMmRhZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOVQxNDQ5MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNzZmOWM1ZmI2ZTZiN2EzNThkNzgwZjFlZWYyYzFiNGI0MDJlOTQ1ZWM4NzdjZGE5ZDZlZmJhOTJlYWRjNjZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.u_X97Q7m8_mKEmK_bEMK4cTEI8uGiRE-oQde8BsSpNg)

โอเคครับ
